export const categories = [
  'Show all',
    'Philosophy',
  'Science',
  'Fantasy',
  "Albanian",
  'Fiction',
  'Non-Fiction',

  'Horror',
  'Mystery',
  'Romance',
  'Dystopian',
  'Classics',
  'Poetry',
  'Drama',
  'Magical Realism',
  'Literary',
  'Modernism',
  'Postcolonial',
  'Feminism',
  'Science Fiction',
  'History',
  'Biography',
  'Economics',
  'Social Commentary',
  'Comics',
  'Humor',
  'Psychology',
  'Theology',
  'Anthropology',
  'Sociology',
  'Satire',
  'Young Adult',
  'Mythology'
];

export const authors = [
  { name: "A.C. Grayling", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Abraham Verghese", genres: ["Fiction", "Literary"] },
  { name: "Adam Smith", genres: ["Philosophy", "Non-Fiction", "Economics"] },
  { name: "Agatha Christie", genres: ["Mystery", "Fiction"] },
  { name: "Alan Moore", genres: ["Fiction", "Fantasy", "Comics"] },
  { name: "Alan Watts", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Albert Camus", genres: ["Philosophy", "Fiction", "Literary"] },
  { name: "Aldous Huxley", genres: ["Fiction", "Dystopian", "Classics"] },
  { name: "Aleksandr Solzhenitsyn", genres: ["Fiction", "Literary", "History"] },
  { name: "Alexander von Humboldt", genres: ["Science", "Non-Fiction"] },
  { name: "Alice Walker", genres: ["Fiction", "Feminism", "Literary"] },
  { name: "Alison Bechdel", genres: ["Fiction", "Comics", "Biography"] },
  { name: "Amartya Sen", genres: ["Philosophy", "Non-Fiction", "Economics"] },
  { name: "Amitav Ghosh", genres: ["Fiction", "Postcolonial", "Literary"] },
  { name: "Amy Tan", genres: ["Fiction", "Literary"] },
  { name: "Anand Giridharadas", genres: ["Non-Fiction", "Social Commentary"] },
  { name: "Angela Davis", genres: ["Non-Fiction", "Feminism", "Social Commentary"] },
  { name: "Anita Desai", genres: ["Fiction", "Postcolonial", "Literary"] },
  { name: "Ann Patchett", genres: ["Fiction", "Literary"] },
  { name: "Annie Ernaux", genres: ["Fiction", "Biography", "Literary"] },
  { name: "Anthony Trollope", genres: ["Fiction", "Classics"] },
  { name: "Anton Chekhov", genres: ["Fiction", "Drama", "Classics"] },
  { name: "Arundhati Roy", genres: ["Fiction", "Postcolonial", "Literary"] },
  { name: "Arthur C. Clarke", genres: ["Science Fiction", "Fiction"] },
  { name: "Arthur Conan Doyle", genres: ["Mystery", "Fiction", "Classics"] },
  { name: "Arthur Schopenhauer", genres: ["Philosophy"] },
  { name: "Augustine of Hippo", genres: ["Philosophy", "Non-Fiction", "Theology"] },
  { name: "Barbara Kingsolver", genres: ["Fiction", "Literary"] },
  { name: "Bell Hooks", genres: ["Non-Fiction", "Feminism", "Social Commentary"] },
  { name: "Benedict Anderson", genres: ["Non-Fiction", "History", "Social Commentary"] },
  { name: "Bertrand Russell", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Bill Bryson", genres: ["Non-Fiction", "History", "Science"] },
  { name: "Bram Stoker", genres: ["Horror", "Fiction", "Classics"] },
  { name: "C.S. Lewis", genres: ["Fantasy", "Fiction", "Non-Fiction"] },
  { name: "Carl Sagan", genres: ["Science", "Non-Fiction"] },
  { name: "Carl Zimmer", genres: ["Science", "Non-Fiction"] },
  { name: "Chimamanda Ngozi Adichie", genres: ["Fiction", "Postcolonial", "Literary"] },
  { name: "Charles Darwin", genres: ["Science", "Non-Fiction"] },
  { name: "Charles Dickens", genres: ["Fiction", "Classics"] },
  { name: "Charlotte Brontë", genres: ["Fiction", "Romance", "Classics"] },
  { name: "Chinua Achebe", genres: ["Fiction", "Postcolonial", "Classics"] },
  { name: "Christopher Hitchens", genres: ["Non-Fiction", "Philosophy", "Social Commentary"] },
  { name: "Claudia Rankine", genres: ["Poetry", "Non-Fiction", "Social Commentary"] },
  { name: "Colm Tóibín", genres: ["Fiction", "Literary"] },
  { name: "Confucius", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Cormac McCarthy", genres: ["Fiction", "Literary"] },
  { name: "D.H. Lawrence", genres: ["Fiction", "Literary", "Classics"] },
  { name: "Daniel C. Dennett", genres: ["Philosophy", "Science", "Non-Fiction"] },
  { name: "Daniel Kahneman", genres: ["Science", "Non-Fiction", "Psychology"] },
  { name: "Dante Alighieri", genres: ["Poetry", "Classics"] },
  { name: "David Foster Wallace", genres: ["Fiction", "Literary", "Non-Fiction"] },
  { name: "David Hume", genres: ["Philosophy", "Non-Fiction"] },
  { name: "David Mitchell", genres: ["Fiction", "Literary"] },
  { name: "Don DeLillo", genres: ["Fiction", "Literary", "Modernism"] },
  { name: "Doris Lessing", genres: ["Fiction", "Literary"] },
  { name: "Douglas Adams", genres: ["Science Fiction", "Fiction", "Humor"] },
  { name: "E.M. Forster", genres: ["Fiction", "Classics", "Literary"] },
  { name: "Edgar Allan Poe", genres: ["Horror", "Fiction", "Poetry", "Classics"] },
  { name: "Edith Wharton", genres: ["Fiction", "Classics", "Literary"] },
  { name: "Edmund Burke", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Edward Said", genres: ["Non-Fiction", "Postcolonial", "Social Commentary"] },
  { name: "Elfriede Jelinek", genres: ["Fiction", "Literary"] },
  { name: "Elie Wiesel", genres: ["Non-Fiction", "Biography", "History"] },
  { name: "Elizabeth Gaskell", genres: ["Fiction", "Classics"] },
  { name: "Emily Brontë", genres: ["Fiction", "Romance", "Classics"] },
  { name: "Emily Dickinson", genres: ["Poetry", "Classics"] },
  { name: "Epictetus", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Epicurus", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Ernest Hemingway", genres: ["Fiction", "Classics", "Literary"] },
  { name: "Evelyn Waugh", genres: ["Fiction", "Literary", "Classics"] },
  { name: "F. Scott Fitzgerald", genres: ["Fiction", "Classics", "Literary"] },
  { name: "Franz Kafka", genres: ["Fiction", "Modernism", "Classics"] },
  { name: "Frantz Fanon", genres: ["Non-Fiction", "Postcolonial", "Philosophy"] },
  { name: "Fredrik Backman", genres: ["Fiction", "Literary"] },
  { name: "Friedrich Nietzsche", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Fyodor Dostoevsky", genres: ["Fiction", "Classics", "Literary"] },
  { name: "Gabriel García Márquez", genres: ["Fiction", "Magical Realism", "Literary"] },
  { name: "George Eliot", genres: ["Fiction", "Classics", "Literary"] },
  { name: "George Orwell", genres: ["Fiction", "Dystopian", "Classics"] },
  { name: "George R.R. Martin", genres: ["Fantasy", "Fiction"] },
  { name: "Gertrude Stein", genres: ["Fiction", "Modernism", "Literary"] },
  { name: "Gilles Deleuze", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Giovanni Boccaccio", genres: ["Fiction", "Classics"] },
  { name: "Gustave Flaubert", genres: ["Fiction", "Classics", "Literary"] },
  { name: "Guy de Maupassant", genres: ["Fiction", "Classics"] },
  { name: "H.G. Wells", genres: ["Science Fiction", "Fiction", "Classics"] },
  { name: "Hannah Arendt", genres: ["Philosophy", "Non-Fiction", "History"] },
  { name: "Harriet Beecher Stowe", genres: ["Fiction", "Classics"] },
  { name: "Haruki Murakami", genres: ["Fiction", "Magical Realism", "Literary"] },
  { name: "Henry David Thoreau", genres: ["Non-Fiction", "Philosophy"] },
  { name: "Henry James", genres: ["Fiction", "Classics", "Literary"] },
  { name: "Herman Melville", genres: ["Fiction", "Classics"] },
  { name: "Hermann Hesse", genres: ["Fiction", "Literary", "Philosophy"] },
  { name: "Hilary Mantel", genres: ["Fiction", "History", "Literary"] },
  { name: "Homer", genres: ["Poetry", "Classics"] },
  { name: "Honoré de Balzac", genres: ["Fiction", "Classics"] },
  { name: "Ian McEwan", genres: ["Fiction", "Literary"] },
  { name: "Immanuel Kant", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Isabel Allende", genres: ["Fiction", "Magical Realism", "Literary"] },
  { name: "Italo Calvino", genres: ["Fiction", "Literary"] },
  { name: "J.D. Salinger", genres: ["Fiction", "Classics", "Literary"] },
  { name: "J.M. Coetzee", genres: ["Fiction", "Literary", "Postcolonial"] },
  { name: "J.R.R. Tolkien", genres: ["Fantasy", "Fiction", "Classics"] },
  { name: "James Baldwin", genres: ["Fiction", "Non-Fiction", "Literary"] },
  { name: "James Joyce", genres: ["Fiction", "Modernism", "Classics"] },
  { name: "Jane Austen", genres: ["Fiction", "Romance", "Classics"] },
  { name: "Jared Diamond", genres: ["Non-Fiction", "Science", "History"] },
  { name: "Jean-Jacques Rousseau", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Jean-Paul Sartre", genres: ["Philosophy", "Fiction", "Literary"] },
  { name: "Jhumpa Lahiri", genres: ["Fiction", "Literary", "Postcolonial"] },
  { name: "Joan Didion", genres: ["Non-Fiction", "Literary"] },
  { name: "Johann Wolfgang von Goethe", genres: ["Fiction", "Poetry", "Classics"] },
  { name: "John Green", genres: ["Fiction", "Young Adult"] },
  { name: "John Locke", genres: ["Philosophy", "Non-Fiction"] },
  { name: "John Milton", genres: ["Poetry", "Classics"] },
  { name: "John Steinbeck", genres: ["Fiction", "Classics", "Literary"] },
  { name: "Jonathan Franzen", genres: ["Fiction", "Literary"] },
  { name: "Jonathan Swift", genres: ["Fiction", "Classics", "Satire"] },
  { name: "Jorge Luis Borges", genres: ["Fiction", "Literary"] },
  { name: "José Saramago", genres: ["Fiction", "Literary"] },
  { name: "Joseph Conrad", genres: ["Fiction", "Classics", "Literary"] },
  { name: "Joseph Heller", genres: ["Fiction", "Literary", "Satire"] },
  { name: "Judith Butler", genres: ["Philosophy", "Non-Fiction", "Feminism"] },
  { name: "Jules Verne", genres: ["Science Fiction", "Fiction", "Classics"] },
  { name: "Julian Barnes", genres: ["Fiction", "Literary"] },
  { name: "Junot Díaz", genres: ["Fiction", "Literary", "Postcolonial"] },
  { name: "Kahlil Gibran", genres: ["Poetry", "Philosophy"] },
  { name: "Karl Marx", genres: ["Philosophy", "Non-Fiction", "Economics"] },
  { name: "Kate Atkinson", genres: ["Fiction", "Literary"] },
  { name: "Kazuo Ishiguro", genres: ["Fiction", "Literary"] },
  { name: "Ken Follett", genres: ["Fiction", "History"] },
  { name: "Khaled Hosseini", genres: ["Fiction", "Literary"] },
  { name: "Kurt Vonnegut", genres: ["Fiction", "Science Fiction", "Literary"] },
  { name: "Lao Tzu", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Laurence Sterne", genres: ["Fiction", "Classics"] },
  { name: "Leo Tolstoy", genres: ["Fiction", "Classics", "Literary"] },
  { name: "Lewis Carroll", genres: ["Fiction", "Fantasy", "Classics"] },
  { name: "Lillian Hellman", genres: ["Drama", "Fiction"] },
  { name: "Liu Cixin", genres: ["Science Fiction", "Fiction"] },
  { name: "Lord Byron", genres: ["Poetry", "Classics"] },
  { name: "Louisa May Alcott", genres: ["Fiction", "Classics"] },
  { name: "Ludwig Wittgenstein", genres: ["Philosophy", "Non-Fiction"] },
  { name: "M.F.K. Fisher", genres: ["Non-Fiction", "Biography"] },
  { name: "Mahmoud Darwish", genres: ["Poetry", "Postcolonial"] },
  { name: "Marcel Proust", genres: ["Fiction", "Classics", "Literary"] },
  { name: "Marcus Aurelius", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Margaret Atwood", genres: ["Fiction", "Dystopian", "Literary"] },
  { name: "Margaret Mead", genres: ["Non-Fiction", "Anthropology"] },
  { name: "Mario Vargas Llosa", genres: ["Fiction", "Literary"] },
  { name: "Mark Twain", genres: ["Fiction", "Classics", "Humor"] },
  { name: "Mary Shelley", genres: ["Fiction", "Science Fiction", "Classics"] },
  { name: "Mary Wollstonecraft", genres: ["Philosophy", "Non-Fiction", "Feminism"] },
  { name: "Maya Angelou", genres: ["Poetry", "Biography", "Non-Fiction"] },
  { name: "Michael Chabon", genres: ["Fiction", "Literary"] },
  { name: "Michel Foucault", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Miguel de Cervantes", genres: ["Fiction", "Classics"] },
  { name: "Milan Kundera", genres: ["Fiction", "Literary"] },
  { name: "Molière", genres: ["Drama", "Classics"] },
  { name: "Montaigne", genres: ["Non-Fiction", "Philosophy"] },
  { name: "Muriel Spark", genres: ["Fiction", "Literary"] },
  { name: "N.K. Jemisin", genres: ["Fantasy", "Fiction"] },
  { name: "Naguib Mahfouz", genres: ["Fiction", "Literary", "Postcolonial"] },
  { name: "Naomi Klein", genres: ["Non-Fiction", "Social Commentary"] },
  { name: "Nathaniel Hawthorne", genres: ["Fiction", "Classics"] },
  { name: "Neil Gaiman", genres: ["Fantasy", "Fiction"] },
  { name: "Ngũgĩ wa Thiong'o", genres: ["Fiction", "Postcolonial", "Literary"] },
  { name: "Nicolaus Copernicus", genres: ["Science", "Non-Fiction"] },
  { name: "Nikolai Gogol", genres: ["Fiction", "Classics"] },
  { name: "Noam Chomsky", genres: ["Non-Fiction", "Philosophy", "Social Commentary"] },
  { name: "Octavia E. Butler", genres: ["Science Fiction", "Fiction"] },
  { name: "Oliver Sacks", genres: ["Non-Fiction", "Science", "Biography"] },
  { name: "Orhan Pamuk", genres: ["Fiction", "Literary"] },
  { name: "Oscar Wilde", genres: ["Fiction", "Drama", "Classics"] },
  { name: "Ovid", genres: ["Poetry", "Classics"] },
  { name: "Patricia Highsmith", genres: ["Mystery", "Fiction"] },
  { name: "Patrick Süskind", genres: ["Fiction", "Literary"] },
  { name: "Paul Auster", genres: ["Fiction", "Literary"] },
  { name: "Pearl S. Buck", genres: ["Fiction", "Classics"] },
  { name: "Peter Singer", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Philip K. Dick", genres: ["Science Fiction", "Fiction"] },
  { name: "Philip Pullman", genres: ["Fantasy", "Fiction"] },
  { name: "Plato", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Ralph Waldo Emerson", genres: ["Non-Fiction", "Philosophy"] },
  { name: "Ray Bradbury", genres: ["Science Fiction", "Fiction", "Classics"] },
  { name: "Rebecca Solnit", genres: ["Non-Fiction", "Feminism"] },
  { name: "René Descartes", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Richard Dawkins", genres: ["Science", "Non-Fiction", "Philosophy"] },
  { name: "Richard Feynman", genres: ["Science", "Non-Fiction"] },
  { name: "Richard Wright", genres: ["Fiction", "Literary"] },
  { name: "Robert A. Heinlein", genres: ["Science Fiction", "Fiction"] },
  { name: "Robert Frost", genres: ["Poetry", "Classics"] },
  { name: "Rudyard Kipling", genres: ["Fiction", "Classics"] },
  { name: "Rumi", genres: ["Poetry", "Philosophy"] },
  { name: "Søren Kierkegaard", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Salman Rushdie", genres: ["Fiction", "Postcolonial", "Literary"] },
  { name: "Samuel Beckett", genres: ["Drama", "Fiction", "Modernism"] },
  { name: "Samuel Johnson", genres: ["Non-Fiction", "Classics"] },
  { name: "Sappho", genres: ["Poetry", "Classics"] },
  { name: "Saul Bellow", genres: ["Fiction", "Literary"] },
  { name: "Seneca", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Shirley Jackson", genres: ["Horror", "Fiction"] },
  { name: "Sigmund Freud", genres: ["Non-Fiction", "Psychology"] },
  { name: "Simone de Beauvoir", genres: ["Philosophy", "Fiction", "Feminism"] },
  { name: "Sinclair Lewis", genres: ["Fiction", "Classics"] },
  { name: "Slavoj Žižek", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Somerset Maugham", genres: ["Fiction", "Classics"] },
  { name: "Sophocles", genres: ["Drama", "Classics"] },
  { name: "Stephen Hawking", genres: ["Science", "Non-Fiction"] },
  { name: "Stephen King", genres: ["Horror", "Fiction"] },
  { name: "Steven Pinker", genres: ["Science", "Non-Fiction"] },
  { name: "Stieg Larsson", genres: ["Mystery", "Fiction"] },
  { name: "Susan Sontag", genres: ["Non-Fiction", "Literary"] },
  { name: "Sylvia Plath", genres: ["Poetry", "Fiction"] },
  { name: "T.S. Eliot", genres: ["Poetry", "Classics"] },
  { name: "Ta-Nehisi Coates", genres: ["Non-Fiction", "Social Commentary"] },
  { name: "Toni Morrison", genres: ["Fiction", "Literary", "Postcolonial"] },
  { name: "Truman Capote", genres: ["Fiction", "Non-Fiction", "Literary"] },
  { name: "Umberto Eco", genres: ["Fiction", "Literary"] },
  { name: "Ursula K. Le Guin", genres: ["Science Fiction", "Fantasy", "Fiction"] },
  { name: "V.S. Naipaul", genres: ["Fiction", "Postcolonial", "Literary"] },
  { name: "Victor Hugo", genres: ["Fiction", "Classics"] },
  { name: "Virginia Woolf", genres: ["Fiction", "Modernism", "Literary"] },
  { name: "Vladimir Nabokov", genres: ["Fiction", "Literary", "Classics"] },
  { name: "Voltaire", genres: ["Philosophy", "Fiction", "Classics"] },
  { name: "W.E.B. Du Bois", genres: ["Non-Fiction", "History", "Social Commentary"] },
  { name: "W.H. Auden", genres: ["Poetry", "Classics"] },
  { name: "Walt Whitman", genres: ["Poetry", "Classics"] },
  { name: "Walter Benjamin", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Wendell Berry", genres: ["Poetry", "Non-Fiction"] },
  { name: "Wilkie Collins", genres: ["Fiction", "Mystery", "Classics"] },
  { name: "William Blake", genres: ["Poetry", "Classics"] },
  { name: "William Faulkner", genres: ["Fiction", "Classics", "Literary"] },
  { name: "William Shakespeare", genres: ["Drama", "Poetry", "Classics"] },
  { name: "Wole Soyinka", genres: ["Drama", "Fiction", "Postcolonial"] },
  { name: "Yann Martel", genres: ["Fiction", "Literary"] },
  { name: "Yasunari Kawabata", genres: ["Fiction", "Literary"] },
  { name: "Yuval Noah Harari", genres: ["Non-Fiction", "History"] },
  { name: "Zadie Smith", genres: ["Fiction", "Literary"] },
  { name: "Zora Neale Hurston", genres: ["Fiction", "Literary", "Postcolonial"] },
  { name: "Émile Zola", genres: ["Fiction", "Classics"] },
  { name: "Aesop", genres: ["Fiction", "Classics"] },
  { name: "Al-Ghazali", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Anaximander", genres: ["Philosophy", "Science"] },
  { name: "Aristotle", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Baruch Spinoza", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Blaise Pascal", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Carol Dweck", genres: ["Non-Fiction", "Psychology"] },
  { name: "Cornel West", genres: ["Philosophy", "Non-Fiction"] },
  { name: "David Sedaris", genres: ["Non-Fiction", "Humor"] },
  { name: "Doris Kearns Goodwin", genres: ["Non-Fiction", "History", "Biography"] },
  { name: "Erich Fromm", genres: ["Non-Fiction", "Psychology"] },
  { name: "Francis Bacon", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Galileo Galilei", genres: ["Science", "Non-Fiction"] },
  { name: "Georg Wilhelm Friedrich Hegel", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Giacomo Leopardi", genres: ["Poetry", "Philosophy"] },
  { name: "Henry Wadsworth Longfellow", genres: ["Poetry", "Classics"] },
  { name: "Herodotus", genres: ["History", "Non-Fiction", "Classics"] },
  { name: "Ibn Rushd", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Isaac Asimov", genres: ["Science Fiction", "Fiction"] },
  { name: "Isaac Newton", genres: ["Science", "Non-Fiction"] },
  { name: "J.K. Rowling", genres: ["Fantasy", "Fiction"] },
  { name: "Jacques Derrida", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Jean Rhys", genres: ["Fiction", "Literary"] },
  { name: "John Kenneth Galbraith", genres: ["Non-Fiction", "Economics"] },
  { name: "John Maynard Keynes", genres: ["Non-Fiction", "Economics"] },
  { name: "John Stuart Mill", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Jonathan Safran Foer", genres: ["Fiction", "Literary"] },
  { name: "Joseph Campbell", genres: ["Non-Fiction", "Mythology"] },
  { name: "Julia Kristeva", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Kenzaburo Oe", genres: ["Fiction", "Literary"] },
  { name: "Kim Stanley Robinson", genres: ["Science Fiction", "Fiction"] },
  { name: "Langston Hughes", genres: ["Poetry", "Literary"] },
  { name: "Marge Piercy", genres: ["Fiction", "Poetry", "Feminism"] },
  { name: "Martin Heidegger", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Mary Beard", genres: ["Non-Fiction", "History"] },
  { name: "Max Weber", genres: ["Non-Fiction", "Sociology"] },
  { name: "Nassim Nicholas Taleb", genres: ["Non-Fiction", "Economics"] },
  { name: "Nawal El Saadawi", genres: ["Fiction", "Feminism", "Postcolonial"] },
  { name: "Niccolò Machiavelli", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Paul Ricoeur", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Percy Bysshe Shelley", genres: ["Poetry", "Classics"] },
  { name: "Petrarch", genres: ["Poetry", "Classics"] },
  { name: "Rachel Carson", genres: ["Science", "Non-Fiction"] },
  { name: "Rebecca Skloot", genres: ["Non-Fiction", "Science", "Biography"] },
  { name: "Rita Dove", genres: ["Poetry"] },
  { name: "Robert Louis Stevenson", genres: ["Fiction", "Classics"] },
  { name: "Roxanne Dunbar-Ortiz", genres: ["Non-Fiction", "History"] },
  { name: "Sheri S. Tepper", genres: ["Science Fiction", "Fiction"] },
  { name: "Siddhartha Mukherjee", genres: ["Non-Fiction", "Science", "Biography"] },
  { name: "Svetlana Alexievich", genres: ["Non-Fiction", "History", "Biography"] },
  { name: "Teju Cole", genres: ["Fiction", "Literary"] },
  { name: "Thomas Hardy", genres: ["Fiction", "Classics"] },
  { name: "Thomas Hobbes", genres: ["Philosophy", "Non-Fiction"] },
  { name: "Thomas Mann", genres: ["Fiction", "Classics", "Literary"] },
  { name: "Thomas Paine", genres: ["Non-Fiction", "Philosophy"] },
  { name: "Thornton Wilder", genres: ["Drama", "Fiction"] },
  { name: "Vikram Seth", genres: ["Fiction", "Literary"] },
  { name: "Wallace Stevens", genres: ["Poetry", "Classics"] },
  { name: "William Wordsworth", genres: ["Poetry", "Classics"] },
  { name: "Yukio Mishima", genres: ["Fiction", "Literary"] },
  { name: "Ismail Kadare", genres: ["Fiction", "Historical Fiction", "Albanian"] },
{ name: "Dritëro Agolli", genres: ["Poetry", "Fiction", "Albanian"] },
{ name: "Gjergj Fishta", genres: ["Poetry", "Epic", "Albanian"] },
{ name: "Naim Frashëri", genres: ["Poetry", "Romanticism", "Albanian"] },
{ name: "Migjeni", genres: ["Poetry", "Prose", "Albanian"] },
{ name: "Luljeta Lleshanaku", genres: ["Poetry", "Contemporary", "Albanian"] },
{ name: "Fatos Kongoli", genres: ["Fiction", "Contemporary", "Albanian"] },
{ name: "Ernest Koliqi", genres: ["Prose", "Fiction", "Albanian"] },
{ name: "Mitrush Kuteli", genres: ["Prose", "Folklore", "Albanian"] },
{ name: "Faik Konica", genres: ["Non-Fiction", "Literary Criticism", "Albanian"] }
];