export const categories = [
  { name: "Philosophy", emoji: "🧠" },
  { name: "Religion", emoji: "🙏" },
  { name: "Evolution", emoji: "🌿" },
  { name: "History", emoji: "📜" },
  { name: "Crime", emoji: "🚨" },
  { name: "Biography", emoji: "👤" },
  { name: "Science", emoji: "🔬" },
    { name: "Universe", emoji: "🌌" },
   { name: "Anthropology ", emoji: "🗿" },
     { name: "Genetics ", emoji: "🧬" },
  { name: "Neuroscience", emoji: "🧪" },
  { name: "Fantasy", emoji: "🧙‍♂️" },

  { name: "Technology", emoji: "💻" },
  { name: "Mythology", emoji: "🐉" },
  {name: "Animals" , emoji:"🫎"},
    { name: "Comics", emoji: "🦸‍♂️" },
  { name: "Politics", emoji: "🏛️" },
  { name: "Art", emoji: "🎨" },
  { name: "Music", emoji: "🎵" },
  { name: "Sports", emoji: "⚽" },
  { name: "Mystery", emoji: "🕵️‍♂️" },
  { name: "Romance", emoji: "💖" },
  { name: "Fiction", emoji: "📖" },
  { name: "Thriller", emoji: "🔪" },
  { name: "Horror", emoji: "👻" },
  { name: "Psychology", emoji: "🧬" },
  { name: "Health", emoji: "🩺" },
  { name: "Economics", emoji: "📊" },
  { name: "Education", emoji: "🎓" },
  { name: "Medical", emoji: "🏥" },
     { name: "Adventure ", emoji: "🌍" },
  {name:"Sociology ", emoji: "🧑‍🤝‍🧑"}
 
];